### ISSUE TITLE
Combining characters

### ISSUE THREAD

**Issue by xfq** [w3c/bp-i18n-specdev#103]
https://w3c.github.io/bp-i18n-specdev/#char_ref_template

> For invisible characters (such as control characters) or for whitespace, the character and its surrounding bdi element should be omitted

I wonder if we should do the same for combining characters, otherwise it will look weird. Another approach is to use a `U+25CC DOTTED CIRCLE` before the combining character.

**Comment by r12a** [comment]
My recommendation for combining marks is:
1. if there's a webfont which supports display with a dotted circle (most Noto fonts do that now), then leave it alone
2. otherwise, use an image – i have a supply of those that can be copied, where appropriate

I don't recommend just dropping the character.

**Comment by xfq** [comment]
Agreed. I'll raise a PR to add this to specdev. Thank you!
