### ISSUE TITLE
include table of examples in section 4.7

### ISSUE THREAD

**Issue by aphillips** [w3c/bp-i18n-specdev#3]
http://w3c.github.io/bp-i18n-specdev/#char_escapes

there are only a few escaping mechanisms in wide use. having a table showing them and showing where they are used would be friendly to users.

**Comment by r12a** [comment]
[from Addison]

Section 4.7 describes character escapes. This issue asked for examples of common escaping mechanisms. I added a table that looks like the screenshot below

![image001](https://user-images.githubusercontent.com/4839211/167405192-00ced522-348d-4134-b2c8-5cba5d37b2ed.png)

**Comment by r12a** [comment]
I think it would be better to move the JavaScript ES6 escape row above the JavaScript (UTF-16) row.

**Comment by aphillips** [comment]
Can you explain your thinking here? Should I also move the `\x` one up so that the `\[ux]{1234}` encodings are together and the `\[uU]` encodings are together? Note that the fixed width `\u` encoding is more common (I think) than the `\u{a}` encoding

**Comment by r12a** [comment]
Main reason for the suggested move is that JS is often used with HTML, so maybe better to have them together and near the top. But also, i'd like to subtely suggest that using real code point values rather than surrogate code point values should be the preferred approach.

But now you made me think about it some more, i'm wondering whether perhaps we should effectively swap the 1st and 2nd column positions... ie. you could have (linearised here because this is markdown):

- HTML, XML  
     - Hex NCRs   
     - Dec NCRs
- JavaScript
     - ES6
     - UTF-16
- Java, Rust, Ruby
    -  ....
     - ....

etc

**Comment by aphillips** [comment]
I like the idea, but it was somewhat complicated. Some escaping schemes (`\u`) are used by a bunch of languages; a few of these also use `\U`. Some provide for the delimited variety. It's complicated. I did break out fixed-vs-variable and tried to clarify. I'm not sure my effort was an improvement :-)

![image](https://user-images.githubusercontent.com/69082/167649610-f21bfb85-e57c-496d-bbe6-fb38a8e90678.png)

What do you think?

**Comment by r12a** [comment]
Hmm. Sorry, but i find that too cluttered and complicated.  Note that i was suggesting making Application col 1, and Type as col 2, but this seems to be further away from the simplification that that would afford.  I don't think we need to define how each escape works; i just saw this as a table of examples.  Therefore, i think the Width column is not needed.  I also think it's better to have the Example col right next to the Description col, since it makes it easier to compare both.

I'm frustrated that i can't quickly code up something to show you because markdown won't allow me and i can't find the source code you've been working with.  If you send me the code for the table in email, i could show you what i mean.

So sorry about that, but for me your changes made things worse rather than better :-(

**Comment by aphillips** [comment]
I agree. I understood what your suggestion was, but it was hard to make it work. Putting the application on the left meant either repeating some of the escapes or repeating the "application" column. How about this:

![image](https://user-images.githubusercontent.com/69082/167667011-b5f1982e-a257-4ead-8415-bdba69bea50a.png)

(Under separate cover sending you the table)

**Comment by r12a** [comment]
I think that's much better!  :-)   Two nitty suggestions:

- drop `(ECMAScript 6 and later)` – these are just examples, and it prevents `JavaScript` looking like a title
- change `Delimited \u` to `\u delimited`,  or `\u....` ; same for \x

**Comment by r12a** [comment]
oh and perhaps:
- change the type of `Java` to `UTF-16 code units`
