### ISSUE TITLE
Consider combining defining language value checklist rules

### ISSUE THREAD

**Issue by stevenatkin** [w3c/bp-i18n-specdev#6]
http://w3c.github.io/bp-i18n-specdev/#lang_values_valid

I would possibly combine some rules into the following:

Values for language declarations must use "well formed" BCP 47 language tags and must use BCP 47 for language tag matching.

Refer to BCP 47, not to RFC 5646.

**Comment by r12a** [comment]
the guidelines here are about two different things that the spec developer may be interested in: (a) declaring language, and (b) matching language.  That's why i kept them separate.  For example, there may come a time when we add more guidelines for matching, and even hive that off into a separate sub section.

**Comment by stevenatkin** [comment]
We can keep them separate.
